### ISSUE TITLE
Fix Motor Issues

### ISSUE THREAD

**Issue by gnawinganimal** [SouthEugeneRoboticsTeam/sertain#24]
It has been observed that the Motors are not perfect. They need to be thoroughly tested.
* `invert` mode is sketchy

**Comment by gnawinganimal** [comment]
A solution to the strange `inverted` behavior has been found. I just needed to set all the followers to `inverted` as well.

**Comment by solidstatebird** [comment]
In the `NeutralMode` enum, `BRAKE` is spelled incorrectly as `BREAK`.

**Comment by gnawinganimal** [comment]
Ok this is more or less fixed with the `maxOutput` being set to one and the naming scheme being figured out.
