### ISSUE TITLE
"Break" mode should be "brake" mode

### ISSUE THREAD

**Issue by andrewda** [SouthEugeneRoboticsTeam/sertain#33]
From now on, I choose to blame "break" mode every time the robot doesn't work.

Related: https://github.com/sertain/sertain-legacy/issues/58

https://github.com/SouthEugeneRoboticsTeam/sertain/blob/a74dc96cc9ed95399597c8d39885535af53e6b80/core/src/main/kotlin/org/sert2521/sertain/motors/MotorController.kt#L277-L280

**Comment by gnawinganimal** [comment]
Hahahaha its not spelled wrong, check the code! Hahahaha...
