### ISSUE TITLE
Fix README typos

### ISSUE THREAD

**Issue by andrewda** [SouthEugeneRoboticsTeam/sertain#45]
https://github.com/SouthEugeneRoboticsTeam/sertain/blob/359781029ce0708931b5555fb7e0a0faf0f7c0f7/README.md#L41

"You can also replace ~~the~~ __`0.0.1` with__ any commit on master ..."

https://github.com/SouthEugeneRoboticsTeam/sertain/blob/359781029ce0708931b5555fb7e0a0faf0f7c0f7/README.md#L54

`RobotRIO` should be `RoboRIO`

**Comment by gnawinganimal** [comment]
Lol
