### ISSUE TITLE
Consider renaming `important` argument in subsytem use

### ISSUE THREAD

**Issue by andrewda** [SouthEugeneRoboticsTeam/sertain#7]
It's difficult to tell (without looking through the source) what `important` does. My first thought was that it would set its thread priority or something like that, instead of its actual use of determining whether an action can run while a subsytem is occupied. In addition, I think it's likely better for `important` to be `false` by default to fall better inline with WPILib standards, and because you don't want to accidentally be running different actions setting the same motors to different speeds (those bugs can be a pain to resolve).

A more descriptive name would be something like `runWhileOccupied = false`, though I'm personally more of a fan of meanlib's `cancelConflicts = true` because it makes it more intuitive what's happening if there does happen to be a conflict.

**Comment by gnawinganimal** [comment]
I agree, its kind of a bad name
Actually, actions can never run while a subsystem is occupied, `important` just makes it so that any current action gets replaced by the new `important` one. But I guess that confusion just goes to show that it is indeed a bad name

**Comment by gnawinganimal** [comment]
Though I can't say I agree to making it false by default. Most of the time you will want to cancel the current action, so it makes sense to have that be the default.

**Comment by andrewda** [comment]
Closed by #10 ✔️
