### ISSUE TITLE
Typesafe subsystem accessors

### ISSUE THREAD

**Issue by gnawinganimal** [SouthEugeneRoboticsTeam/sertain#9]
Right now it is still possible to forget to include subsystems in a use function. For example:
```
use(Drivetrain) {
	Climber.climb() // oops
}
```

Here is a way to improve this. If we have the user configure a task using some sort of function, then we can use a react hooks like syntax to require the subsystems, and then use them in an action. Like this:
```
doTask {
	val drivetrain = useDrivetrain()
	val climber = useClimber()
	action {
		climber.climb()
	}
}
```
If we use a `DslMarker`, then we can actually prevent `use` functions from being called in the `action` block.

Subsystem accessors would be created like this:

```
val (useDrivetrain) = Drivetrain.accessor
```

Also if anyone thinks of a better names for the functions than `doTask` and `action` please comment because the names are really not that good

**Comment by andrewda** [comment]
Closed by #10 ✔️
